// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Board Builder → Wheels*
 */
export interface BoardBuilderDocumentDataWheelsItem {
  /**
   * Texture field in *Board Builder → Wheels*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: board_builder.wheels[].texture
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  texture: prismic.ImageField<never>;

  /**
   * UID field in *Board Builder → Wheels*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: board_builder.wheels[].uid
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  uid: prismic.KeyTextField;
}

/**
 * Item in *Board Builder → Decks*
 */
export interface BoardBuilderDocumentDataDecksItem {
  /**
   * Texture field in *Board Builder → Decks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: board_builder.decks[].texture
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  texture: prismic.ImageField<never>;

  /**
   * UID field in *Board Builder → Decks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: board_builder.decks[].uid
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  uid: prismic.KeyTextField;
}

/**
 * Item in *Board Builder → Metals*
 */
export interface BoardBuilderDocumentDataMetalsItem {
  /**
   * Color field in *Board Builder → Metals*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: board_builder.metals[].color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  color: prismic.ColorField;

  /**
   * UID field in *Board Builder → Metals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: board_builder.metals[].uid
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  uid: prismic.KeyTextField;
}

/**
 * Content for Board Builder documents
 */
interface BoardBuilderDocumentData {
  /**
   * Wheels field in *Board Builder*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: board_builder.wheels[]
   * - **Tab**: Wheels
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  wheels: prismic.GroupField<Simplify<BoardBuilderDocumentDataWheelsItem>> /**
   * Decks field in *Board Builder*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: board_builder.decks[]
   * - **Tab**: Decks
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */;
  decks: prismic.GroupField<Simplify<BoardBuilderDocumentDataDecksItem>> /**
   * Metals field in *Board Builder*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: board_builder.metals[]
   * - **Tab**: Metals
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */;
  metals: prismic.GroupField<Simplify<BoardBuilderDocumentDataMetalsItem>>;
}

/**
 * Board Builder document from Prismic
 *
 * - **API ID**: `board_builder`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BoardBuilderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BoardBuilderDocumentData>,
    "board_builder",
    Lang
  >;

type DemoDocumentDataSlicesSlice = HeroSlice;

/**
 * Content for Demo documents
 */
interface DemoDocumentData {
  /**
   * Slice Zone field in *Demo*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: demo.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<DemoDocumentDataSlicesSlice> /**
   * Meta Title field in *Demo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: demo.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Demo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: demo.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Demo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: demo.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Demo document from Prismic
 *
 * - **API ID**: `demo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DemoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<DemoDocumentData>, "demo", Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | BoardBuilderDocument
  | DemoDocument
  | SettingsDocument;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Button field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BoardBuilderDocument,
      BoardBuilderDocumentData,
      BoardBuilderDocumentDataWheelsItem,
      BoardBuilderDocumentDataDecksItem,
      BoardBuilderDocumentDataMetalsItem,
      DemoDocument,
      DemoDocumentData,
      DemoDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
    };
  }
}
